# Generated by Django 6.0.5 on 2026-05-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
