# Generated by Django 6.0.5 on 2026-05-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0002_alter_skill_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devilfruit',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
