# Generated by Django 6.0.5 on 2026-05-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0003_alter_devilfruit_slug_alter_monster_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
