# Generated by Django 6.0.5 on 2026-05-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0004_skill_view_count_alter_scenario_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devilfruit',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='monster',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
